{% set name = "serialchemy" %}
{% set version = "1.0.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 27a052ce966320583e638785acefc1da2f3a054ce6970e06772dbf20a8a6121b

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools_scm
  run:
    - python >=3.8
    - sqlalchemy >=1.4, <2.0

test:
  imports:
    - serialchemy
    - serialchemy._tests

about:
  home: http://github.com/ESSS/serialchemy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Serializers for SQLAlchemy models.
  doc_url: https://serialchemy.readthedocs.io/
  dev_url: http://github.com/ESSS/serialchemy

extra:
  recipe-maintainers:
    - lincrosenbach
    - kfasolin
    - nicoddemus
    - lvoliveira
