{% set name = "serialchemy" %}
{% set version = "1.0.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 66c5a715c0da19372a016ea84fdbd06799b1eed87904a668d6d554507d399a9f

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - sqlalchemy >=1.4,<2.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - serialchemy
    - serialchemy._tests

about:
  home: http://github.com/ESSS/serialchemy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Serializers for SQLAlchemy models.
  doc_url: https://serialchemy.readthedocs.io/
  dev_url: http://github.com/ESSS/serialchemy

extra:
  recipe-maintainers:
    - lincrosenbach
    - kfasolin
    - nicoddemus
    - lvoliveira
