{% set name = "serialchemy" %}
{% set version = "1.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 65826c02fd57713d8ccf32e0f8ba61a01bafbd7652b546d32edb84923ac79732

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools_scm
  run:
    - python >=3.8
    - sqlalchemy >=1.4, <2.0

test:
  imports:
    - serialchemy
    - serialchemy._tests

about:
  home: http://github.com/ESSS/serialchemy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Serializers for SQLAlchemy models.
  doc_url: https://serialchemy.readthedocs.io/
  dev_url: http://github.com/ESSS/serialchemy

extra:
  recipe-maintainers:
    - lincrosenbach
    - kfasolin
    - nicoddemus
