travis:
  secure:
    BINSTAR_TOKEN: jzrf+dhF2Ri04by+A5obbFNq8lYJJXGNLTNBYtW3gERXas3OHaNHH1NNOGVmZtcFBRH7BH8I5Cza2bWg7IzkzVR9CX1IO7hngGM71OyzFC0xs4rYVNBr4AISB+/Vtj4ExLxOCuzT5ZSyM3Ah/DvQ/YMut7OcvAEv3xrfvfdPnUc8MKeSwlJLTDtAw33DlWF+Wdc8Tp9Fpi7IbEfAymxcR0aHg9jSZa2I75voqch8dm6cMpmXtdHd1RcKBLCckbR9DVh0T6GswifvbNpvaDpwzlRkgwGb6Qfjch2/7ncXJkbWjczFEuhn0VGua/bDVIcMB29NFjqBrl11SvOPrHZ+7JTvrAWuxRMMB3SrYVr15+4QxwEjwDhZKd9GWTl2+PkcjyrwZqYUxmA2cgR7BiyN5IXEHpcBrYhtCqzg5q32L155GSKwALbUplk2CIRHEqWXHTK/I6t0jns4qz4lUupKEyPn5F2F7Ru5JRD9pe7M7KdJMNbcbqce87ZBHoBZjyse10IE54YjKYFYRn/CWdbc0tuEEFO7/LMk6Rny7n4lBr2pQdWrjd9TQ1MQVabsCRNzpQyi2Db6JYMe7p5C+rYfW4Gta+dKQrnh9LRjwvNtt9uVFPM/wcmtXY015+A9F36fnSGWqPSA17aU0fBgvwW9TfGwbOcyv49Tsadq07DWGcA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
