travis:
  secure:
    BINSTAR_TOKEN: SjRnXRN6T0gY8PUZKWqbyhTZLQFPS1dxFa25+G9WD1FPP54obLNrYAxXvVx959jXW29DX5OCbHwwAHGVm3RokLPNdzc3QHggaxQmL111LX5nUYigIzFOWl+8eKLfnNJ2JZ4FNm92rOfgOM8FtFRSjPuRzRVUADAbQHhhYAisic7bmbM3nZfjPwAoRXEgHlK5LWNnuVu0MrIW3sOpibbSANU+cRoEwjs7WZQSRZBu+2KJENHPQ6rjOlouaZE7sZVAePcFN88iGuZOJQKveczOu6ORkltzT2+lMNf997OuY7LmV031gRTHwMQwCpTYlZAuT86Nqi+c+iVFsJhVs78OWOU4+0Pc/cd/fZ2NE0WFhZqCfha9JkpRc3HVOCqUrLMgUsebFxf2cuI6jxKyMwch6i5UidYvIaQ6DibSiLiPpdGK5Uos7aK2yw3HBc13WH812rZxx+a5B+C/+TvccgJI4uJD2MOOfk08nX+t4FQ/DCyeUOGZwAjzhbBKbBv7L9mPL63zEXX0L574NksiFZ0SXqxIqX554TaLVCpuEkGArxlDmS+MebHVuqcpevbnm8wKM/ziEEyngX/63bRWXPVMiiCzaDGu7aM1G5MBt0cMXO0yL1hneZXtgPGsE54YUqqxv2keIPWQyS3yCjf0OYYb4mm5SXneym9PjavKtNQdgJI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
